import { Heart, MessageCircle, MoreHorizontal, Search, Image, X, Home, Bell, UserRound, Settings, LogOut, Sun, Moon } from 'lucide-react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { useState, type FormEvent } from 'react';
import { useApp } from './store';
import type { Post, User as UserType } from './types';
export const Avatar=({user,size=42}:{user:UserType;size?:number})=><img className="avatar" style={{width:size,height:size}} src={user.avatar} alt={user.name}/>;
export function Sidebar(){const {currentUser,notifications,logout,dark,toggleDark}=useApp();const nav=useNavigate();const unread=notifications.filter(n=>!n.read).length;const items=[[Home,'Home','/'],[Search,'Explore','/search'],[Bell,'Notifications','/notifications'],[UserRound,'Profile',`/profile/${currentUser.id}`],[Settings,'Settings','/settings']] as const;return <aside className="sidebar"><Link className="brand" to="/">vibely<span>✦</span></Link><nav>{items.map(([Icon,label,to])=><NavLink key={label} to={to} end={to==='/' }><Icon size={20}/>{label}{label==='Notifications'&&unread>0&&<b>{unread}</b>}</NavLink>)}</nav><div className="side-bottom"><button onClick={toggleDark}>{dark?<Sun size={19}/>:<Moon size={19}/>}{dark?'Light mode':'Dark mode'}</button><button onClick={()=>{logout();nav('/login')}}><LogOut size={19}/>Log out</button><Link className="account" to={`/profile/${currentUser.id}`}><Avatar user={currentUser}/><span>{currentUser.name}<small>@{currentUser.username.replace('@','')}</small></span></Link></div></aside>}
export function MobileNav(){const {currentUser,notifications}=useApp();return <nav className="mobile-nav"><NavLink to="/"><Home/></NavLink><NavLink to="/search"><Search/></NavLink><NavLink to="/notifications"><Bell/>{notifications.some(n=>!n.read)&&<i/>}</NavLink><NavLink to={`/profile/${currentUser.id}`}><Avatar user={currentUser} size={25}/></NavLink></nav>}
export function Composer(){const {currentUser,createPost}=useApp();const [text,setText]=useState('');const [image,setImage]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();createPost(text,image||undefined);setText('');setImage('')};return <form className="composer" onSubmit={submit}><Avatar user={currentUser}/><div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Share your vibe..."/><div className="compose-actions"><button type="button" className="icon-btn" onClick={()=>setImage(image?'':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80')}><Image size={19}/>{image?'Remove image':'Add photo'}</button><button className="primary" disabled={!text.trim()}>Post</button></div></div></form>}
export function PostCard({post}:{post:Post}){const {users,currentUser,toggleLike,comment,deletePost}=useApp();const [show,setShow]=useState(false);const [text,setText]=useState('');const user=users.find(u=>u.id===post.userId)!;const liked=post.likes.includes('me');return <article className="post"><div className="post-head"><Link to={`/profile/${user.id}`}><Avatar user={user}/></Link><div><Link to={`/profile/${user.id}`} className="post-name">{user.name}</Link><span>@{user.username.replace('@','')} · {post.createdAt}</span></div>{post.userId==='me'&&<button title="Delete post" className="plain menu" onClick={()=>deletePost(post.id)}><X size={18}/></button>}</div><p>{post.text}</p>{post.image&&<img className="post-image" src={post.image} alt="Post attachment"/>}<div className="post-actions"><button className={liked?'liked':''} onClick={()=>toggleLike(post.id)}><Heart size={20} fill={liked?'currentColor':'none'}/>{post.likes.length||''}</button><button onClick={()=>setShow(s=>!s)}><MessageCircle size={20}/>{post.comments.length||''}</button><button className="more"><MoreHorizontal size={20}/></button></div>{show&&<div className="comments">{post.comments.map(c=>{const author=users.find(u=>u.id===c.userId)!;return <div className="comment" key={c.id}><Avatar user={author} size={27}/><span><b>{author.name}</b>{c.text}</span></div>})}<form onSubmit={e=>{e.preventDefault();comment(post.id,text);setText('')}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a comment..."/><button disabled={!text.trim()}>Send</button></form></div>}</article>}
export function People({title='People you may like'}:{title?:string}){const {users,currentUser,toggleFollow}=useApp();return <section className="people"><h3>{title}</h3>{users.filter(u=>u.id!=='me').slice(0,3).map(u=>{const following=currentUser.following.includes(u.id);return <div className="person" key={u.id}><Avatar user={u}/><Link to={`/profile/${u.id}`}><b>{u.name}</b><span>@{u.username.replace('@','')}</span></Link><button onClick={()=>toggleFollow(u.id)} className={following?'following':''}>{following?'Following':'Follow'}</button></div>})}</section>}
